### ISSUE TITLE
Running version of vocab-recommender

### ISSUE THREAD

**Issue by rezacsedu** [istavrak/vocab-recommender#1]
Hi,

Where can I access the running version of vocab-recommender?

**Comment by istavrak** [comment]
Hi Rezaul,

The best option would be to set it up locally. You could give it a try on the heroku platform, but it's running on a free plan with limited resources: https://vocab-recommender.herokuapp.com. Also, the deployment is based on the _no-nlp_ branch of this repo.

Thank you for your interest in the approach!
